[33mcommit 47eaa3d353f83bccaa9f68c5a83c309f25ac59b2[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmaster[m[33m)[m
Author: Saad Malik <saadmalik9748@gmail.com>
Date:   Fri Aug 22 09:59:26 2025 +0500

    Successfully configure and run all Docker services with Uvicorn

[1mdiff --git a/backend/Dockerfile b/backend/Dockerfile[m
[1mindex e69de29..c52bae5 100644[m
[1m--- a/backend/Dockerfile[m
[1m+++ b/backend/Dockerfile[m
[36m@@ -0,0 +1,14 @@[m
[32m+[m[32m# Stage 1: Build[m
[32m+[m[32mFROM python:3.11-slim AS builder[m
[32m+[m[32mWORKDIR /app[m
[32m+[m[32mCOPY requirements.txt .[m
[32m+[m[32mRUN pip install --user -r requirements.txt[m
[32m+[m[32mRUN ls -l /root/.local/bin/uvicorn > /install_check.txt[m
[32m+[m
[32m+[m[32m# Stage 2: Runtime[m
[32m+[m[32mFROM python:3.11-slim[m
[32m+[m[32mWORKDIR /app[m
[32m+[m[32mCOPY requirements.txt .[m
[32m+[m[32mRUN pip install -r requirements.txt[m
[32m+[m[32mCOPY ./app ./app[m
[32m+[m[32mCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"][m
\ No newline at end of file[m
[1mdiff --git a/backend/requirements.txt b/backend/requirements.txt[m
[1mindex e69de29..24566bc 100644[m
[1m--- a/backend/requirements.txt[m
[1m+++ b/backend/requirements.txt[m
[36m@@ -0,0 +1,5 @@[m
[32m+[m[32mfastapi==0.115.0[m
[32m+[m[32muvicorn==0.30.6[m
[32m+[m[32mwebsockets==12.0[m
[32m+[m[32mcelery==5.4.0[m
[32m+[m[32mredis==5.0.8[m
\ No newline at end of file[m
[1mdiff --git a/docker-compose.yml b/docker-compose.yml[m
[1mindex e69de29..3e3573f 100644[m
[1m--- a/docker-compose.yml[m
[1m+++ b/docker-compose.yml[m
[36m@@ -0,0 +1,26 @@[m
[32m+[m[32mservices:[m
[32m+[m[32m  backend:[m
[32m+[m[32m    build: ./backend[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8000:8000"[m
[32m+[m[32m    restart: unless-stopped[m
[32m+[m[32m  stt:[m
[32m+[m[32m    build: ./services/stt[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8001:8001"[m
[32m+[m[32m    restart: unless-stopped[m
[32m+[m[32m  translation:[m
[32m+[m[32m    build: ./services/translation[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8002:8002"[m
[32m+[m[32m    restart: unless-stopped[m
[32m+[m[32m  tts:[m
[32m+[m[32m    build: ./services/tts[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8003:8003"[m
[32m+[m[32m    restart: unless-stopped[m
[32m+[m[32m  image:[m
[32m+[m[32m    build: ./services/image[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8004:8004"[m
[32m+[m[32m    restart: unless-stopped[m
\ No newline at end of file[m
[1mdiff --git a/path.txt b/path.txt[m
[1mnew file mode 100644[m
[1mindex 0000000..3826740[m
[1m--- /dev/null[m
[1m+++ b/path.txt[m
[36m@@ -0,0 +1 @@[m
[32m+[m[32m/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin[m
[1mdiff --git a/services/image/Dockerfile b/services/image/Dockerfile[m
[1mindex b66ed49..c9ea848 100644[m
[1m--- a/services/image/Dockerfile[m
[1m+++ b/services/image/Dockerfile[m
[36m@@ -7,7 +7,7 @@[m [mRUN pip install --user -r requirements.txt[m
 # Stage 2: Runtime[m
 FROM python:3.11-slim[m
 WORKDIR /app[m
[31m-COPY --from=builder /root/.local /root/.local[m
[32m+[m[32mCOPY requirements.txt .[m
[32m+[m[32mRUN pip install -r requirements.txt[m
 COPY ./main.py ./main.py[m
[31m-ENV PATH=/root/.local/bin:$PATH[m
 CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004"][m
[1mdiff --git a/services/image/requirements.txt b/services/image/requirements.txt[m
[1mindex e69de29..1c61ca3 100644[m
[1m--- a/services/image/requirements.txt[m
[1m+++ b/services/image/requirements.txt[m
[36m@@ -0,0 +1,2 @@[m
[32m+[m[32mfastapi==0.115.0[m
[32m+[m[32muvicorn==0.30.6[m
\ No newline at end of file[m
[1mdiff --git a/services/stt/Dockerfile b/services/stt/Dockerfile[m
[1mindex a4590fb..b8cd3b8 100644[m
[1m--- a/services/stt/Dockerfile[m
[1m+++ b/services/stt/Dockerfile[m
[36m@@ -3,6 +3,7 @@[m [mFROM python:3.11-slim AS builder[m
 WORKDIR /app[m
 COPY requirements.txt .[m
 RUN pip install --user -r requirements.txt[m
[32m+[m[32mRUN ls -l /root/.local/bin/uvicorn > /install_check.txt[m
 [m
 # Stage 2: Runtime[m
 FROM python:3.11-slim[m
[36m@@ -10,4 +11,5 @@[m [mWORKDIR /app[m
 COPY --from=builder /root/.local /root/.local[m
 COPY ./main.py ./main.py[m
 ENV PATH=/root/.local/bin:$PATH[m
[32m+[m[32mRUN echo $PATH > /path.txt[m
 CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"][m
\ No newline at end of file[m
[1mdiff --git a/services/stt/docker-compose.yml b/services/stt/docker-compose.yml[m
[1mnew file mode 100644[m
[1mindex 0000000..5b35aa0[m
[1m--- /dev/null[m
[1m+++ b/services/stt/docker-compose.yml[m
[36m@@ -0,0 +1,24 @@[m
[32m+[m[32mversion: '3.8'[m
[32m+[m[32mservices:[m
[32m+[m[32m  backend:[m
[32m+[m[32m    build: ./backend[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8000:8000"[m
[32m+[m[32m    volumes:[m
[32m+[m[32m      - ./backend:/app[m
[32m+[m[32m  stt:[m
[32m+[m[32m    build: ./services/stt[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8001:8001"[m
[32m+[m[32m  translation:[m
[32m+[m[32m    build: ./services/translation[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8002:8002"[m
[32m+[m[32m  tts:[m
[32m+[m[32m    build: ./services/tts[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8003:8003"[m
[32m+[m[32m  image:[m
[32m+[m[32m    build: ./services/image[m
[32m+[m[32m    ports:[m
[32m+[m[32m      - "8004:8004"[m
\ No newline at end of file[m
[1mdiff --git a/services/stt/requirements.txt b/services/stt/requirements.txt[m
[1mindex e69de29..1c61ca3 100644[m
[1m--- a/services/stt/requirements.txt[m
[1m+++ b/services/stt/requirements.txt[m
[36m@@ -0,0 +1,2 @@[m
[32m+[m[32mfastapi==0.115.0[m
[32m+[m[32muvicorn==0.30.6[m
\ No newline at end of file[m
[1mdiff --git a/services/translation/Dockerfile b/services/translation/Dockerfile[m
[1mindex 78be802..015814d 100644[m
[1m--- a/services/translation/Dockerfile[m
[1m+++ b/services/translation/Dockerfile[m
[36m@@ -7,7 +7,7 @@[m [mRUN pip install --user -r requirements.txt[m
 # Stage 2: Runtime[m
 FROM python:3.11-slim[m
 WORKDIR /app[m
[31m-COPY --from=builder /root/.local /root/.local[m
[32m+[m[32mCOPY requirements.txt .[m
[32m+[m[32mRUN pip install -r requirements.txt[m
 COPY ./main.py ./main.py[m
[31m-ENV PATH=/root/.local/bin:$PATH[m
 CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"][m
\ No newline at end of file[m
[1mdiff --git a/services/translation/requirements.txt b/services/translation/requirements.txt[m
[1mindex e69de29..1c61ca3 100644[m
[1m--- a/services/translation/requirements.txt[m
[1m+++ b/services/translation/requirements.txt[m
[36m@@ -0,0 +1,2 @@[m
[32m+[m[32mfastapi==0.115.0[m
[32m+[m[32muvicorn==0.30.6[m
\ No newline at end of file[m
[1mdiff --git a/services/tts/Dockerfile b/services/tts/Dockerfile[m
[1mindex ddf12b2..99baeb3 100644[m
[1m--- a/services/tts/Dockerfile[m
[1m+++ b/services/tts/Dockerfile[m
[36m@@ -7,7 +7,7 @@[m [mRUN pip install --user -r requirements.txt[m
 # Stage 2: Runtime[m
 FROM python:3.11-slim[m
 WORKDIR /app[m
[31m-COPY --from=builder /root/.local /root/.local[m
[32m+[m[32mCOPY requirements.txt .[m
[32m+[m[32mRUN pip install -r requirements.txt[m
 COPY ./main.py ./main.py[m
[31m-ENV PATH=/root/.local/bin:$PATH[m
 CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"][m
\ No newline at end of file[m
[1mdiff --git a/services/tts/requirements.txt b/services/tts/requirements.txt[m
[1mindex e69de29..1c61ca3 100644[m
[1m--- a/services/tts/requirements.txt[m
[1m+++ b/services/tts/requirements.txt[m
[36m@@ -0,0 +1,2 @@[m
[32m+[m[32mfastapi==0.115.0[m
[32m+[m[32muvicorn==0.30.6[m
\ No newline at end of file[m
