version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  stt:
    build: ./services/stt
    ports:
      - "8001:8001"
  translation:
    build: ./services/translation
    ports:
      - "8002:8002"
  tts:
    build: ./services/tts
    ports:
      - "8003:8003"
  image:
    build: ./services/image
    ports:
      - "8004:8004"